---
version: "3"
services:
 devopsdb:
   image: cp11640/webapp:dbimage
   ports:
     - "3306:3306"

 application:
   image: cp11640/webapp:appimage
   ports:
     - "1111:8080"
   depends_on:
     - "devopsdb"
